default: &default
  adapter: postgresql
  template: template0
  encoding: unicode
  reconnect: false
  pool: 10
  username: admin
  password: root

development:
  <<: *default
  database: pratama_polykem_development

test:
  <<: *default
  database: pratama_polykem_test

production:
  <<: *default
  database: pratama_polykem