default: &default
  adapter: postgresql
  pool: 10
  username: admin
  password: root
  host: localhost

staging:
  <<: *default
  database: enterprise_staging

development:
  <<: *default
  database: enterprise_dev

test:
  <<: *default
  database: enterprise_test

production:
  <<: *default
  database: enterprise
